[versions]
activity = "1.10.1"
androidGradlePlugin = "8.10.1"
accompanist = "0.36.0"
androidx-hilt = "1.2.0"
androidx-junit = "1.2.1"
browser = "1.8.0"
coil = "3.2.0"
composeBom = "2025.06.01"
core = "1.16.0"
epoxy = "5.1.4"
espresso = "3.6.1"
gplayapi = "3.5.6"
hiddenapibypass = "6.1"
hilt = "2.56.2"
hiltWork = "1.2.0"
junit = "4.13.2"
kotlin = "2.1.20"
ksp = "2.1.20-1.0.32" # New versions depends upon KSP2 which conflicts with epoxy
ktlint = "12.1.2"
leakcanary = "2.14"
libsu = "6.0.0"
lifecycle = "2.9.1"
material = "1.12.0"
navigation = "2.9.0"
okhttp = "4.12.0"
preference = "1.2.1"
processPhoenix = "3.0.0"
protobufJavalite = "4.31.1"
rikkaHiddenAPI = "4.3.3"
rikkaTools = "4.4.0"
room = "2.4.3"
serialization = "1.8.1"
shimmer = "0.5.0"
shizuku = "13.1.5"
swiperefreshlayout = "1.1.0"
truth = "1.4.4"
viewpager2 = "1.1.0"
work = "2.10.2"
emv = "0.1.2"

# @keep
compileSdk = "36"
# @keep
minSdk = "24"
# @keep
#noinspection ExpiredTargetSdkVersion
targetSdk = "25"
# @keep
pagseguroMinSdk = "23"
# @keep
pagseguroTargetSdk = "24"
# @keep
stoneMinSdk = "22"
# @keep
stoneTargetSdk = "34"

firebaseCrashlyticsBuildtools = "3.0.4"
cardview = "1.0.0"
zxing = "4.3.0"
zxingCore = "3.5.3"
viewModelCompose = "2.9.1"
retrofit = "3.0.0"
okhttpLogging = "4.12.0"
datastore = "1.0.0"
playServicesMeasurementApi = "22.5.0"
lottie = "6.6.7"
composeDestinations = "1.8.42-beta"
reactivexJava = "2.2.21"
reactivexAndroid = "2.1.1"
plugpag = "1.30.51"
stoneSdkVersion = "4.11.6"
playServicesGamesV2 = "21.0.0"
androidSupportDesign = "28.0.0"


[libraries]
destinations-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "composeDestinations" }
emv-qrcode = { module = "com.github.mvallim:emv-qrcode", version.ref = "emv" }
destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }
plugpagservice-wrapper = { module = "br.com.uol.pagseguro.plugpagservice.wrapper:wrapper", version.ref = "plugpag" }

stone-sdk-envconfig = { module = "br.com.stone.sdk.android:envconfig", version.ref = "stoneSdkVersion" }
stone-sdk = { module = "br.com.stone:stone-sdk", version.ref = "stoneSdkVersion" }
stone-sdk-posandroid = { module = "br.com.stone:stone-sdk-posandroid", version.ref = "stoneSdkVersion" }
stone-sdk-sunmi = { module = "br.com.stone:stone-sdk-posandroid-sunmi", version.ref = "stoneSdkVersion" }
stone-sdk-positivo = { module = "br.com.stone:stone-sdk-posandroid-positivo", version.ref = "stoneSdkVersion" }
stone-sdk-ingenico = { module = "br.com.stone:stone-sdk-posandroid-ingenico", version.ref = "stoneSdkVersion" }
stone-sdk-gertec = { module = "br.com.stone:stone-sdk-posandroid-gertec", version.ref = "stoneSdkVersion" }
stone-sdk-tectoy = { module = "br.com.stone:stone-sdk-posandroid-gertec", version.ref = "stoneSdkVersion" }
android-support-design = { module = "com.android.support:design", version.ref = "stoneSdkVersion" }

lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
airbnb-epoxy-android = { module = "com.airbnb.android:epoxy", version.ref = "epoxy" }
airbnb-epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxy" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-junit" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
auroraoss-gplayapi = { module = "com.auroraoss:gplayapi", version.ref = "gplayapi" }
coil-kt = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
github-topjohnwu-libsu = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
google-android-material = { module = "com.google.android.material:material", version.ref = "material" }
google-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
google-truth = { module = "com.google.truth:truth", version.ref = "truth" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-core = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-androidx-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
hilt-androidx-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
lsposed-hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "processPhoenix" }
rikka-hidden-stub = { module = "dev.rikka.hidden:stub", version.ref = "rikkaHiddenAPI" }
rikka-shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
rikka-shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
rikka-tools-refine-runtime = { module = "dev.rikka.tools.refine:runtime", version.ref = "rikkaTools" }
squareup-leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxingCore" }
zxing = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-materialWindow = { module = "androidx.compose.material3:material3-window-size-class" }
material = { module = "com.google.android.material:material", version.ref = "material" }
accompanist-themeadapter-material = { module = "com.google.accompanist:accompanist-themeadapter-material", version.ref = "accompanist" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLogging" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-preferences-rxjava2 = { group = "androidx.datastore", name = "datastore-preferences-rxjava2", version = "1.0.0" }
play-services-measurement-api = { group = "com.google.android.gms", name = "play-services-measurement-api", version.ref = "playServicesMeasurementApi" }
reactivex-java = { module = "io.reactivex.rxjava2:rxjava", version.ref = "reactivexJava" }
reactivex-android = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "reactivexAndroid" }
play-services-games-v2 = { group = "com.google.android.gms", name = "play-services-games-v2", version.ref = "playServicesGamesV2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidx-navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
rikka-tools-refine-plugin = { id = "dev.rikka.tools.refine", version.ref = "rikkaTools" }
